Comisiones/Models/CO_tb_Premios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_Premios
    {
        public int id_premio { get; set; }
        public string nombre_premio { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public string CreadoUsuario { get; set; }
        public Nullable<System.DateTime> Creado_F { get; set; }
        public string UltModUsuario { get; set; }
        public Nullable<System.DateTime> UltMod_F { get; set; }
    }
}

Comisiones/Controllers/CO_tb_PremiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Comisiones.Models;
using Comisiones.Models.ModelsEvolution;
using Comisiones.Data;

namespace Comisiones.Controllers
{
     public class CO_tb_PremiosController : Controller
    {
        
        private herbaxEntities db = new herbaxEntities();
        private EvolutionEntities Evo = new EvolutionEntities();
        private EVO_PTEntities EvoPT = new EVO_PTEntities();
        private string nameController = "ReembolsosCanjeController";//nombre que se usa para generar elArchivo LOG (Archivo LOG por controlador)
        private string rutaArchivoLog = @"C:\herbax\Logs\";
        

        // GET: CO_tb_Premios
        public ActionResult Index()
        {
            
            return View(db.CO_tb_Premios.Where(x=> x.Estatus == true).ToList());
        }

        // GET: CO_tb_Premios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CO_tb_Premios cO_tb_Premios = db.CO_tb_Premios.Find(id);
            if (cO_tb_Premios == null)
            {
                return HttpNotFound();
            }


            ViewBag.Premios = db.CO_tb_Premios.Where(x => x.id_premio == id).ToList();

            Log oLog = new Log(rutaArchivoLog);
            List<CO_st_BuscaProductosConUnId1_Result> LProductos = new List<CO_st_BuscaProductosConUnId1_Result>();

            using (herbaxEntities hbxEntities = new herbaxEntities())
            {
                try
                {
                    ViewBag.dropdownPaises = new SelectList(Evo.CL_tb_Pais.ToList().Where(x => x.Id_Estatus == 1), "Id_Pais", "Pais");

                    var Periodos = from o in Evo.CO_tb_Periodo.ToList()
                                   where o.Estatus == 1
                                   select new SelectListItem
                                   {
                                       Text = o.Id_Periodo.ToString(),
                                       Value = o.Id_Periodo.ToString(),
                                   };
                    ViewBag.dropdownPeriodos = Periodos.ToList();

                    List<SelectListItem> estatus = new List<SelectListItem>()
                        {
                            new SelectListItem { Text = "Activo", Value = "1" },
                            new SelectListItem { Text = "Inactivo", Value = "0" },
                        };

                    ViewBag.IsOK = 0;
                    ViewBag.dropdownEstatus = estatus;

                    var Opcion = 3;
                    int Id = cO_tb_Premios.id_premio;
                    int Rank = 0;
                    int IdPais = int.Parse(cO_tb_Premios.id_pais.ToString());

                    //LProductos = hbxEntities.CO_st_BuscaProductos4(IdPais).ToList();
                    LProductos = hbxEntities.CO_st_BuscaProductosConUnId5(IdPais, Id, Rank, Opcion).ToList();
                    return View(LProductos.ToList());
                }
                catch (Exception ex)
                {
                    ViewBag.IsOK = 0;
                    var Col = 0;
                    var resultado = "";

                    resultado = ex.InnerException.Message.ToString();
                    Col = resultado.IndexOf("\r");

                    if (Col.ToString() == "")
                    {
                        var NewString = resultado.Substring(0, Col);
                        ViewBag.Message = NewString;
                    }
                    else
                    {
                        ViewBag.Message = resultado;
                    }
                    return View();
                }
            }

        }

        // GET: CO_tb_Premios/Create
        public ActionResult Create(int? id_pais)
        {
            if (id_pais != null)
            {
                Log oLog = new Log(rutaArchivoLog);
                List<CO_st_BuscaProductos4_Result> LProductos = new List<CO_st_BuscaProductos4_Result>();

                using (herbaxEntities hbxEntities = new herbaxEntities())
                {
                    try
                    {
                        ViewBag.dropdownPaises = new SelectList(Evo.CL_tb_Pais.ToList().Where(x => x.Id_Estatus == 1), "Id_Pais", "Pais");

                        var Periodos = from o in Evo.CO_tb_Periodo.ToList()
                                       where o.Estatus == 1
                                       select new SelectListItem
                                       {
                                           Text = o.Id_Periodo.ToString(),
                                           Value = o.Id_Periodo.ToString(),
                                       };
                        ViewBag.dropdownPeriodos = Periodos.ToList();

                        List<SelectListItem> estatus = new List<SelectListItem>()
                        {
                            new SelectListItem { Text = "Activo", Value = "1" },
                            new SelectListItem { Text = "Inactivo", Value = "0" },
                        };

                        ViewBag.IsOK = 0;
                        ViewBag.dropdownEstatus = estatus;


                        var idPais = id_pais;
                        LProductos = hbxEntities.CO_st_BuscaProductos4(idPais).ToList();

                        return View(LProductos.ToList());
                    }
                    catch (Exception ex)
                    {
                        ViewBag.IsOK = 0;
                        var Col = 0;
                        var resultado = "";

                        resultado = ex.InnerException.Message.ToString();
                        Col = resultado.IndexOf("\r");

                        if (Col.ToString() == "")
                        {
                            var NewString = resultado.Substring(0, Col);
                            ViewBag.Message = NewString;
                        }
                        else
                        {
                            ViewBag.Message = resultado;
                        }
                        return View();
                    }
                }

            }
            else
            {
                Log oLog = new Log(rutaArchivoLog);
                List<CO_st_BuscaProductos4_Result> LProductos = new List<CO_st_BuscaProductos4_Result>();

                using (herbaxEntities hbxEntities = new herbaxEntities())
                {
                    try
                    {
                        ViewBag.dropdownPaises = new SelectList(Evo.CL_tb_Pais.ToList().Where(x => x.Id_Estatus == 1), "Id_Pais", "Pais");

                        var Periodos = from o in Evo.CO_tb_Periodo.ToList()
                                       where o.Estatus == 1
                                       select new SelectListItem
                                       {
                                           Text = o.Id_Periodo.ToString(),
                                           Value = o.Id_Periodo.ToString(),
                                       };
                        ViewBag.dropdownPeriodos = Periodos.ToList();

                        List<SelectListItem> estatus = new List<SelectListItem>()
                        {
                            new SelectListItem { Text = "Activo", Value = "1" },
                            new SelectListItem { Text = "Inactivo", Value = "0" },
                        };

                        ViewBag.IsOK = 0;
                        ViewBag.dropdownEstatus = estatus;

                        var idPais = 1;
                        LProductos = hbxEntities.CO_st_BuscaProductos4(idPais).ToList();

                        return View(LProductos.ToList());
                    }
                    catch (Exception ex)
                    {
                        ViewBag.IsOK = 0;
                        var Col = 0;
                        var resultado = "";

                        resultado = ex.InnerException.Message.ToString();
                        Col = resultado.IndexOf("\r");

                        if (Col.ToString() == "")
                        {
                            var NewString = resultado.Substring(0, Col);
                            ViewBag.Message = NewString;
                        }
                        else
                        {
                            ViewBag.Message = resultado;
                        }
                        return View();
                    }
                }
            }

        }

        // POST: CO_tb_Premios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(IList<CO_st_BuscaProductosPremios_Result> entity)
        {
            try
            {
                //var NomUsuario = Session["IdNombre"].ToString();
                //var Usuarios = db.CO_tb_Usuarios.Where(x => (x.NombreUsuario == NomUsuario)).FirstOrDefault();
                //var varUsuario = Usuarios.IdUsuario;

                CO_tb_Premios Premios = new CO_tb_Premios();

                foreach (var item in entity) /// aqui es
                {
                    Premios.nombre_premio = item.nombre_premio;
                    Premios.id_pais = item.Id_Pais;
                    Premios.id_periodo = item.Id_Periodo;
                    Premios.Estatus = true;
                    Premios.Pagado = false;
                }
               
                db.CO_tb_Premios.Add(Premios);
                db.SaveChanges();

                var IdPremio = 0;

Comisiones/Views/CO_tb_Premios/Create.cshtml
@model IList<Comisiones.Models.CO_st_BuscaProductos4_Result>

@{ ViewBag.Title = "Alta de Premios";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<script type="text/javascript" class="init">

</script>


<head>
	<link rel="stylesheet" href="~/Content/estilos.css" />
</head>

<body>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")

	<main>
		<div class="maintitle">Lista de reembolsos pendientes</div>
		<div class="container-fluid" id="divMainContainer" style="align-content:center">
			<form id="myform" class="form-inline">
				@using (Html.BeginForm())
				{
					@Html.AntiForgeryToken()

				<div class="form-horizontal">
					<hr />
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@using (Html.BeginForm("Create", "CO_tb_Premios", FormMethod.Get))
					{
						<div class="form-group">
							<div class="col-md-2" style="text-align-last:right">
								<div>
									<label>Pais</label>
								</div>
							</div>

							<div class="col-md-8">
								@Html.DropDownList("id_pais", (IEnumerable<SelectListItem>)ViewBag.dropdownPaises, "Selecciona un Pais?", new { onchange = "this.form.submit();", @id = "IdPais", @class = "form-control" })								
							</div>

						</div>
					}


					<div class="form-group">
						<div class="col-md-2" style="text-align-last:right">
							<div>
								<label>Nombre Premio</label>
							</div>
						</div>

						<div class="col-md-10">
							<input maxlength="800" class="form-control" id="nombre_premio" name="nombre_premio" style="width:800px;height:30px;" tabindex="1" type="text">
						</div>
					</div>

					<br />
					<div class="form-group">
						<div class="col-md-2" style="text-align-last:right">
							<div>
								<label>Periodo</label>
							</div>
						</div>
						<div class="col-md-10">
							@Html.DropDownList("id_periodo", (IEnumerable<SelectListItem>)ViewBag.dropdownPeriodos, new { @id = "IdPeriodo", @class = "form-control" })
						</div>
					</div>
					<br />

					<br />
					<br />
					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							@*<a href=#myModal" id="MuestraProd">Abrir ventana modal</a>*@
							<input data-ajax="true" value="Seleccionar Productos" id="MuestraProd" class="btn btn-danger btn-lg" href="#myModal" name="MuestraProd" data-toggle="modal" />
						</div>
					</div>
				</div>
				}

				@*<div>
						@Html.ActionLink("Back to List", "Index")
					</div>*@






			</form>

			<!-- Modal -->
			<div id="myModal" class="modal face" style="align-content:center">
				<div class="modal-body" role="document">
					<div class="modal-content">
						<div class="modal-body form-horizontal">
							@using (Html.BeginForm("Create", "CO_tb_Premios", "POST"))
							{
								<table class="table table-striped modal-content theader w-auto" id="TblPremios">

									<tr style="background-color:#D6EAF8;width:100%">
										<th>Empresa</th>
										<th>Nombre de Premio</th>
										<th></th>
										<th>Periodo</th>
										
									</tr>

									<tr class="tablaPremios"></tr>
								</table>
								<table class="table display" style="background-color:#D6EAF8" id="TblProductos">
									<thead style="background-color:#D6EAF8">
										<tr>
											<th style="text-align:center">
												<label>Clave</label>
											</th>
											<th style="width:700px;" type="text" maxlength="700">
												<label>Nombre Producto</label>
											</th>
											<th>
												<label>Precio</label>
											</th>
											<th>
												<label>Seleccionar</label>
											</th>
											<th>
												@*<label></label>*@
											</th>
											<th>
											</th>
											<th>
											</th>

										</tr>
									</thead>
									<tbody>

										@for (var i = 0; i < Model.Count; i++)
										{
											<tr id="row+@i" oninput="test(this)">

												@Html.HiddenFor(x => x[i].PrecioPublico, new { @class = "form-control  TmpVentas", @id = "Precio" + @i })
												@Html.HiddenFor(x => x[i].sku, new { @class = "form-control TmpSku" })
												@Html.HiddenFor(x => x[i].Descripcion, new { @class = "form-control", @style = "align-items:right", @disabled = "disabled" })
												@*@Html.HiddenFor(x => x[i].SubTotal, new { @class = "form-control Monto", @style = "align-items:right", @disabled = "disabled" })*@

												@Html.HiddenFor(x => x[i].Warehouse_ID, new { @class = "form-control" })
												@Html.HiddenFor(x => x[i].Warehouse, new { @class = "form-control" })
												@Html.HiddenFor(x => x[i].cve_art, new { @class = "form-control" })
												@*@Html.HiddenFor(x => x[i].ActivoSAE, new { @class = "form-control TmpAnio" })
												@Html.HiddenFor(x => x[i].PrecioMinimo, new { @class = "form-control TmpMes" })*@

												<td style="text-align:center">
													@Html.DisplayFor(x => x[i].sku, new { @class = "form-control" })
												</td>



												<td style="width:700px;" type="text" maxlength="700">
													@Html.DisplayFor(x => x[i].Descripcion, new { @class = "form-control", @style = "align-items:right", @disabled = "disabled" })
												</td>
												<td>

													@Html.DisplayFor(x => x[i].PrecioPublico, new { @class = "form-control VaPrecio" + @i, @style = "align-items:right", @disabled = "disabled" })
												</td>
												<td>
													@*@Html.EditorFor(x => x[i].CantidadProducto, "Teclee la cantidad a solicitar", new { @class = "form-control CantProd", htmlAttributes = new { min = 0, max = 100000 }, @style = "align-items:right; width: 80px; height: 20px;", @type = "number" })
														<br />
														@Html.ValidationMessageFor(x => x[i].CantidadProducto, "", new { @class = "text-danger" })*@

													@Html.CheckBoxFor(x => x[i].checkeado, new { @class = "form-control", @style = "align-items:left" })
												</td>
												@*<td>
														@Html.HiddenFor(x => x[i].SubTotal, new { @class = "form-control TmpMonto", @style = "align-items:right", @disabled = "disabled" })
													</td>*@
												<td>
													@Html.HiddenFor(x => x[i].Id_Empresa, new { @class = "form-control  IdEmpresa" })
												</td>
												@*<td>
														@Html.HiddenFor(x => x[i].Id_Socio, new { @class = "form-control  TmpSocio" })
													</td>*@
													<td>
														@Html.HiddenFor(x => x[i].nombre_premio, new { @class = "form-control  TmpNomPremio" })
													</td>
												<td>
													@Html.HiddenFor(x => x[i].Id_Pais, new { @class = "form-control  TmpPais" })
												</td>
												<td>
													@Html.HiddenFor(x => x[i].Id_Periodo, new { @class = "form-control  TmpPeriodo" })
												</td>
												@*<td>
													@Html.HiddenFor(x => x[i].Cantidad, new { @class = "form-control  TmpCantidad" })
												</td>
												<td>
													@Html.HiddenFor(x => x[i].Topada, new { @class = "form-control  TmpTopada" })
												</td>
												<td>
													@Html.HiddenFor(x => x[i].Porcentaje, new { @class = "form-control  TmpPorcentaje" })
												</td>*@
											</tr>
										}
									</tbody>

								</table>



								<div class="modal-footer">
									<input type="hidden" value="0" id="rembolsoTotal" />
									<input type="hidden" value="0" id="rembolsoActual" />

									<a href="~/CO_tb_ConfigReembolsos/" class="btn btn-danger btn-lg">Cerrar</a>

									@*<input type="submit" value="envia" onclick="return validar()" class="btn btn-danger btn-lg" />*@
									<input type="submit" value="envia" class="btn btn-danger btn-lg" />

								</div>
							}
						</div>
					</div>
				</div>


			</div>
		</div>
	</main>
</body>




@section scripts{

	<script type="text/javascript">
		$(document).ready(function () {

			mostrarLoader();
			//$("#IdPeriodos").attr('readonly', true);
			//$("#IdPais").change(function()
			//{
			//    // Clear drop down list
			//    $("#IdPeriodos").find("option").remove();

			//    var params =
			//            {
			//                IdPais: $("#IdPais").val(),
			//            };
			//    $.ajax(
			//        {
			//            url: "/CO_tb_Premios/PeriodosSelectList",
			//            method: "post",
			//            data: params,
			//            success: function(data) {
			//                console.log(data)
			//                // agregamos opcion de inicio
			//                $('<option>').val(0).text("Periodo a capturar?").appendTo("#IdPeriodos");

			//                $.each(data, function(index, value) {
			//                    console.log(index + value)
			//                    $('<option>').val(value.Value).text(value.Text).appendTo("#IdPeriodos");
			//                })

			//                $("#IdPeriodos").attr('readonly', false);
			//            },
			//        });
			//})


			$(".CantProd").val(0);
			$(".text-box").val(0);


			var Nombre = 0;//global variable
			var Ventas = 0;//global variable
			var TotalReembolso = 0;//global variable

			var Reembolsado = "";
			var NumSocio = "";
			var Diferencia = 0;
			var Anio = 0;
			var Mes = 0;
			var Quincena = 0;


			ocultarLoader();



			$("#MuestraProd").click(function () {
				addRowHandlers();
			})


		});



		function addRowHandlers() {
			$('#myform').on('submit', function (ev) {
				$('#my-modal').modal({
					show: 'false'
				});

				window.opener.document.getElementById('myModal').innerHTML = "";

				var data = $(this).serializeObject();
				json_data = JSON.stringify(data);
				$("#results").text(json_data);
				$(".modal-body").text(json_data);

				ev.preventDefault();
			});


			var hoy = new Date();
			var dd = hoy.getDate();
			var mm = hoy.getMonth() + 1;
			var yyyy = hoy.getFullYear();

			if (dd < 10) {
				dd = '0' + dd;
			}

			if (mm < 10) {
				mm = '0' + mm;
			}

			var PaisPremio = $("#IdPais").val();
			var PeriodoPremio = $("#IdPeriodo").val();
			var NombrePremio = $("#nombre_premio").val();

			$(".TmpNomPremio").val(NombrePremio);
			$(".TmpPais").val(PaisPremio);
			$(".TmpPeriodo").val(PeriodoPremio);
			
			var ProdASeleccionar = " <td>" + PaisPremio.toString()  + "</td><td>" + PeriodoPremio.toString() + "</td><td>" + NombrePremio.toString() + "</td>";
			$(".tablaPremios td").remove();
			$(".tablaPremios").append(ProdASeleccionar);
		};


		function validar() {
			return false
		}


		function test(item) {
		};



		function cierre() {
			$("#myModal").modal('hide');//ocultamos el modal
			$('body').removeClass('modal-open');//eliminamos la clase del body para poder hacer scroll
			$('.modal-backdrop').remove();//eliminamos el backdrop del modal

			Swal.fire
				({
					title: 'Aun no ha grabado el pedido esta seguro que quiere ',
					text: "Presione el boton para cerrar!",
					type: "success",
					animation: false,
					customClass:
					{
						popup: 'animated tada'
					}
				}).then(function (result) {
					window.location.hostname;
				})

		}


		function cerrar() {

			$(".CantProd").text("0");
			$(".text-box").text("0");
		}


		function validar() {
			return false
		}


		$("#IdPais").change(function () {
			$("input[type=submit]").click();
		});
	</script>



}

<style>
	.theader th {
		width: 16% !important;
	}

	.theader td {
		width: 16% !important;
	}
</style>

Comisiones/Views/CO_tb_Premios/Index.cshtml
@model IEnumerable<Comisiones.Models.CO_tb_Premios>

@{
    ViewBag.Title = "Listado de Premios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="maintitle">Listado de Reembolsos</div>

<br />
<div class="container-fluid" id="divMainContainer">
    @Html.AntiForgeryToken()
    <p>
        @Html.ActionLink("Agregar nueva", "Create", "CO_tb_Premios", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
        @Html.AntiForgeryToken()
    </p>



    <script type="text/javascript" class="init">
        $(document).ready(function () {
            var table = $('#tblConfigReembolsos').DataTable({

                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ registros",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Ningún dato disponible en esta tabla",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            }
			);


        });
    </script>


    <div class="col-lg-12" id="divPageQueryLists">
        <table id="tblConfigReembolsos" class="table display table-striped table-bordered dt-responsive nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.id_premio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.nombre_premio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.id_pais)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.id_periodo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Estatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Pagado)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.CreadoUsuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Creado_F)
                    </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.UltModUsuario)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UltMod_F)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.id_premio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre_premio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.id_pais)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.id_periodo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Estatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Pagado)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.CreadoUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Creado_F)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.UltModUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UltMod_F)
                        </td>
                        <td>
                            @Html.ActionLink("Modificar", "Edit", new { id = item.id_premio }) |
                            @Html.ActionLink("Consultar", "Details", new { id = item.id_premio }) |
                            @Html.ActionLink("Borrar", "Delete", new { id = item.id_premio })
                        </td>
                    </tr>
                }

        </table>
    </div>