Comisiones/Models/CO_tb_ImpuestoComision.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comisiones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_tb_ImpuestoComision
    {
        public int id_Impuesto { get; set; }
        public Nullable<decimal> limiteInferior { get; set; }
        public Nullable<decimal> limiteSuperior { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> coutaFija { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaMovimiento { get; set; }
    }
}

Comisiones/Controllers/CO_tb_ImpuestoComisionController.cs
using Comisiones.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Comisiones.Controllers
{
    public class CO_tb_ImpuestoComisionController : Controller
    {
        private herbaxEntities db = new herbaxEntities();
        // GET: CO_tb_ImpuestoComision
        public ActionResult Index()
        {
            var VarRol = 0;
            if (Session["idRol"] != null)
            {
                VarRol = int.Parse(Session["idRol"].ToString());
            }
            else
            {
                return Redirect("~/Home/Login");
            }


            if (!db.CO_tb_PermisosRoles.Any(x => x.IdPantalla == 29 && x.IdRol == VarRol))
            {
                return Redirect("~/Home/SinPermiso");
            }
            else
            {
                return View(db.CO_tb_ImpuestoComision.ToList());
            }
        }

        // GET: CO_tb_ImpuestoComision/Details/5
        public ActionResult Details(int? id)
        {
            var VarRol = 0;
            if (Session["idRol"] != null)
            {
                VarRol = int.Parse(Session["idRol"].ToString());
            }
            else
            {
                return Redirect("~/Home/Login");
            }


            if (!db.CO_tb_PermisosRoles.Any(x => x.IdPantalla == 17 && x.IdRol == VarRol))
            {
                return Redirect("~/Home/Index");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CO_tb_ImpuestoComision cO_tb_ImpuestoComision = db.CO_tb_ImpuestoComision.Find(id);
                if (cO_tb_ImpuestoComision == null)
                {
                    return HttpNotFound();
                }
                return View(cO_tb_ImpuestoComision);
            }
        }

        // GET: CO_tb_ImpuestoComision/Create
        public ActionResult Create()
        {
            var VarRol = 0;
            if (Session["idRol"] != null)
            {
                VarRol = int.Parse(Session["idRol"].ToString());
            }
            else
            {
                return Redirect("~/Home/Login");
            }


            if (!db.CO_tb_PermisosRoles.Any(x => x.IdPantalla == 17 && x.IdRol == VarRol))
            {
                return Redirect("~/Home/Index");
            }
            else
            {
                return View();
            }
        }

        // POST: CO_tb_ImpuestoComision/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Impuesto,limiteInferior,limiteSuperior,porcentaje,coutaFija,usuario,fechaMovimiento")] CO_tb_ImpuestoComision cO_tb_ImpuestoComision)
        {
            if (ModelState.IsValid)
            {
                var NomUsuario = Session["IdNombre"].ToString();
                cO_tb_ImpuestoComision.usuario = NomUsuario;
                cO_tb_ImpuestoComision.fechaMovimiento = System.DateTime.Now;

                cO_tb_ImpuestoComision.usuario = NomUsuario;
                cO_tb_ImpuestoComision.fechaMovimiento = System.DateTime.Now;

                db.CO_tb_ImpuestoComision.Add(cO_tb_ImpuestoComision);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cO_tb_ImpuestoComision);
        }

        // GET: CO_tb_ImpuestoComision/Edit/5
        public ActionResult Edit(int? id)
        {

            var VarRol = 0;
            if (Session["idRol"] != null)
            {
                VarRol = int.Parse(Session["idRol"].ToString());
            }
            else
            {
                return Redirect("~/Home/Login");
            }


            if (!db.CO_tb_PermisosRoles.Any(x => x.IdPantalla == 17 && x.IdRol == VarRol))
            {
                return Redirect("~/Home/Index");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                CO_tb_ImpuestoComision cO_tb_ImpuestoComision = db.CO_tb_ImpuestoComision.Find(id);
                if (cO_tb_ImpuestoComision == null)
                {
                    return HttpNotFound();
                }
                return View(cO_tb_ImpuestoComision);
            }
        }

        // POST: CO_tb_ImpuestoComision/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Impuesto,limiteInferior,limiteSuperior,porcentaje,coutaFija,usuario,fechaMovimiento")] CO_tb_ImpuestoComision cO_tb_ImpuestoComision)
        {
            if (ModelState.IsValid)
            {
                var NomUsuario = Session["IdNombre"].ToString();
                //var Usuarios = db.CO_tb_Usuarios.Where(x => (x.NombreUsuario == NomUsuario)).FirstOrDefault();
                //var VarUsuario = Usuarios.IdUsuario;

                cO_tb_ImpuestoComision.usuario = NomUsuario;
                cO_tb_ImpuestoComision.fechaMovimiento = System.DateTime.Now;

                db.Entry(cO_tb_ImpuestoComision).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cO_tb_ImpuestoComision);
        }

        // GET: CO_tb_ImpuestoComision/Delete/5
        public ActionResult Delete(int? id)
        {
            var VarRol = 0;
            if (Session["idRol"] != null)
            {
                VarRol = int.Parse(Session["idRol"].ToString());
            }
            else
            {
                return Redirect("~/Home/Login");
            }

            if (!db.CO_tb_PermisosRoles.Any(x => x.IdPantalla == 17 && x.IdRol == VarRol))
            {
                return Redirect("~/Home/Index");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CO_tb_ImpuestoComision cO_tb_ImpuestoComision = db.CO_tb_ImpuestoComision.Find(id);
            if (cO_tb_ImpuestoComision == null)
            {
                return HttpNotFound();
            }
            return View(cO_tb_ImpuestoComision);
        }

        // POST: CO_tb_ImpuestoComision/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CO_tb_ImpuestoComision cO_tb_ImpuestoComision = db.CO_tb_ImpuestoComision.Find(id);
            db.CO_tb_ImpuestoComision.Remove(cO_tb_ImpuestoComision);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Comisiones/Views/CO_tb_ImpuestoComision/Create.cshtml
@model Comisiones.Models.CO_tb_ImpuestoComision

@{
	ViewBag.Title = "Alta de Impuestos de Comisiones";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 jumbotron" style="color:#000000; font:caption; background-color:azure;">
	<h2>Agregar nuevo</h2>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>Crear nuevo impuesto de comisiones</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="form-group">
				@Html.LabelFor(model => model.limiteInferior, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.limiteInferior, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.limiteInferior, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.limiteSuperior, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.limiteSuperior, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.limiteSuperior, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.porcentaje, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.porcentaje, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.porcentaje, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.coutaFija, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.coutaFija, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.coutaFija, "", new { @class = "text-danger" })
				</div>
			</div>

			@*<div class="form-group">
				@Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.fechaMovimiento, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.fechaMovimiento, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.fechaMovimiento, "", new { @class = "text-danger" })
				</div>
			</div>*@

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Grabar" class="btn btn-default" style="height:25Px; text-align:inherit" />
					@Html.ActionLink("Regresar", "Index", "CO_tb_ImpuestoComision", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
				</div>
			</div>
		</div>

	}
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Comisiones/Views/CO_tb_ImpuestoComision/Delete.cshtml
@model Comisiones.Models.CO_tb_ImpuestoComision

@{
	ViewBag.Title = "Delete";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-12 jumbotron" style="color:#000000; font:caption; background-color:azure;">
	<h2>Borrar esta compañia</h2>

	@Html.AntiForgeryToken()
	<h6>Esta seguro que desea borrar los datos de esta compañia?</h6>
	<div>
		<div>
			<hr />
			<dl class="dl-horizontal">
				<dt>
					@Html.DisplayNameFor(model => model.limiteInferior)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.limiteInferior)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.limiteSuperior)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.limiteSuperior)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.porcentaje)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.porcentaje)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.coutaFija)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.coutaFija)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.usuario)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.usuario)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.fechaMovimiento)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.fechaMovimiento)
				</dd>

			</dl>

			@using (Html.BeginForm())
			{
				@Html.AntiForgeryToken()

				<div class="form-actions no-color">
					<input type="submit" value="Aceptar" class="btn btn-default" />
					@Html.ActionLink("Regresar", "Index", "CO_tb_ImpuestoComision", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
				</div>
			}
		</div>


	</div>

</div>

Comisiones/Views/CO_tb_ImpuestoComision/Details.cshtml
@model Comisiones.Models.CO_tb_ImpuestoComision

@{
	ViewBag.Title = "Consultas";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<div class="col-md-12 jumbotron" style="color:#000000; font:caption; background-color:azure;">
	@Html.AntiForgeryToken()
	<h2>Consultar Compañias de Pago</h2>
	<div>
		<h4>Informacion de la Compañia</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.limiteInferior)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.limiteInferior)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.limiteSuperior)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.limiteSuperior)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.porcentaje)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.porcentaje)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.coutaFija)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.coutaFija)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.usuario)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.usuario)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.fechaMovimiento)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.fechaMovimiento)
			</dd>

		</dl>
	</div>
	<p>
		@Html.ActionLink("Regresar", "Index", "CO_tb_ImpuestoComision", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
	</p>

</div>


@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Comisiones/Views/CO_tb_ImpuestoComision/Edit.cshtml
@model Comisiones.Models.CO_tb_ImpuestoComision

@{
	ViewBag.Title = "Modificaciones";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12 jumbotron" style="color:#000000; font:caption; background-color:azure;">
	<h2>Modificar datos</h2>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>Cambios a la informacion</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.id_Impuesto)

			<div class="form-group">
				@Html.LabelFor(model => model.limiteInferior, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.limiteInferior, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.limiteInferior, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.limiteSuperior, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.limiteSuperior, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.limiteSuperior, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.porcentaje, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.porcentaje, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.porcentaje, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.coutaFija, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.coutaFija, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.coutaFija, "", new { @class = "text-danger" })
				</div>
			</div>


			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Grabar" class="btn btn-default" style="height:25Px; text-align:inherit" />
					@Html.ActionLink("Regresar", "Index", "CO_tb_ImpuestoComision", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
				</div>
			</div>
		</div>
	}
</div>

Comisiones/Views/CO_tb_ImpuestoComision/Index.cshtml
@model IEnumerable<Comisiones.Models.CO_tb_ImpuestoComision>

@{
	ViewBag.Title = "Altas";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="maintitle">Listado de Impuesto de Comisiones</div>

<br />
<div class="container-fluid" id="divMainContainer">
	@Html.AntiForgeryToken()
	<p>
		@Html.ActionLink("Agregar nueva", "Create", "CO_tb_ImpuestoComision", null, new { @class = "btn btn-default btn-lg", @style = "display:inline" })
		@Html.AntiForgeryToken()
	</p>


	<script type="text/javascript" class="init">
		$(document).ready(function () {
			var table = $('#tblCompaniaPago').DataTable({

				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					"infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ registros",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Ningún dato disponible en esta tabla",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				}
			}
			);


		});
	</script>


	<div class="col-lg-12" id="divPageQueryLists">
		<table id="tblCompaniaPago" class="table display table-striped table-bordered dt-responsive nowrap" style="width:100%; text-align:right;">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.limiteInferior)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.limiteSuperior)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.porcentaje)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.coutaFija)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.usuario)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.fechaMovimiento)
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.limiteInferior)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.limiteSuperior)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.porcentaje)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.coutaFija)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.usuario)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.fechaMovimiento)
						</td>
						<td>
							@Html.ActionLink("Modificar", "Edit", new { id = item.id_Impuesto }) |
							@Html.ActionLink("Consultar", "Details", new { id = item.id_Impuesto }) |
							@Html.ActionLink("Borrar", "Delete", new { id = item.id_Impuesto })
						</td>
					</tr>
				}
			</tbody>

		</table>
	</div>
</div>